version: "3"
services:
  elasticsearch:
    image: docker.io/elasticsearch:7.5.1
    container_name: elasticsearch
    volumes:
      - /Users/zhongwenweilai/doker/elk/elasticsearch/conf/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - /Users/zhongwenweilai/docker/elk/elasticsearch/data:/usr/share/elasticsearch/data/:rw
      - /Users/zhongwenweilai/docker/elk/elasticsearch/logs:/usr/share/elasticsearch/logs/:rw
    ports:
      - "9200:9200"
      - "9300:9300"
    restart: always

  kibana:
    image: docker.io/kibana:7.5.1
    container_name: kibana
    volumes:
      - /Users/zhongwenweilai/docker/elk/kibana/conf/kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    restart: always

  logstash:
    image: logstash:7.5.1
    container_name: logstash
    command: logstash -f /usr/share/logstash/config/logstash.conf
    volumes:
      - /Users/zhongwenweilai/docker/elk/logstash/config/:/usr/share/logstash/config
      - /Users/zhongwenweilai/docker/elk/logstash/data/:/usr/share/logstash/data
    ports:
      - "9600:9600"
      - "5044:5044"
    depends_on:
      - elasticsearch
    restart: always
